# Generated by Django 4.2.3 on 2023-07-10 22:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("summary", models.TextField(max_length=100)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("creation_date", models.DateTimeField(auto_now=True)),
                ("done", models.BooleanField(default=False)),
            ],
        ),
    ]
